Major function comment updates; simplified some code in exit_script_on_failure and print_stream info; changed print_stream_info  behavior to match function comment; made the (no option) command into the [w]atch command for streamers whose names start with other command characters; add caching of time subscribed streamers were last seen online

diff --git a/wtwitch b/wtwitch
--- a/wtwitch
+++ b/wtwitch
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 #
 # Description: Browse and watch Twitch without being tracked.
+#    Homepage: https://git.sr.ht/~krathalan/wtwitch
 #
 # Copyright (C) 2019-2020:
 readonly CONTRIBUTORS="krathalan, nycko123, Léo Villeveygoux"
@@ -62,7 +63,6 @@ set -Eeuo pipefail
 
 # Script (self) information
 readonly SCRIPT_NAME="${0##*/}"
-readonly PROJECT_URL="https://git.sr.ht/~krathalan/wtwitch"
 readonly VERSION="1.7"
 
 # Subscription check cache
@@ -81,6 +81,7 @@ readonly CACHE_GAME_ID_FILE="${CACHE_FILE_DIRECTORY}/gameids.json"
 
 # Config
 readonly CONFIG_FILE_DIRECTORY="${XDG_CONFIG_HOME:-${HOME}/.config}/${SCRIPT_NAME}"
+readonly LAST_SEEN_DIRECTORY="${CONFIG_FILE_DIRECTORY}/lastSeen"
 readonly CONFIG_FILE="${CONFIG_FILE_DIRECTORY}/config.json"
 readonly BLOCKLIST_FILE="${CONFIG_FILE_DIRECTORY}/blocklist"
 
@@ -211,12 +212,6 @@ readonly TRANSLATIONS="$(cat <<EOF
     "es": "Error",
     "fr": "Érreur"
   },
-  "exiting": {
-    "en": "Exiting",
-    "de": "Verlassen von",
-    "es": "Saliendo de",
-    "fr": "Fermeture de"
-  },
   "print_help": {
     "en": "View the man page at",
     "de": "View the man page at",
@@ -340,7 +335,8 @@ EOF
 # -----------------------------------------
 
 # Check files -- create cache/config directories and required files
-mkdir -p "${CONFIG_FILE_DIRECTORY}" "${CACHE_FILE_DIRECTORY}"
+# Creating LAST_SEEN_DIRECTORY also creates CONFIG_FILE_DIRECTORY
+mkdir -p "${LAST_SEEN_DIRECTORY}" "${CACHE_FILE_DIRECTORY}"
 touch "${BLOCKLIST_FILE}"
 
 if [[ ! -f "${CACHE_GAME_ID_FILE}" ]]; then
@@ -449,6 +445,9 @@ write_setting()
 # Globals:
 #   TWITCH_API_KEY
 #   TWITCH_API_SECRET
+#   TWITCH_ID_URL
+#   apiToken
+#   curlFlags
 # Arguments:
 #   none
 # Returns:
@@ -498,10 +497,13 @@ clean_up()
 }
 
 #######################################
-# Downloads a file quietly using curl and passes the TWITCH_API_KEY as a header to the server. Returns the downloaded file.
+# Downloads a file quietly using curl and passes the
+# TWITCH_API_KEY as a header to the server. Returns the
+# downloaded file.
 # Globals:
-#   apiToken
 #   TWITCH_API_KEY
+#   apiToken
+#   curlFlags
 # Arguments:
 #   $1: file to download
 # Returns:
@@ -514,10 +516,10 @@ download_file()
 }
 
 #######################################
-# Prints passed error message before premature exit. Prints everything to >&2 (STDERR).
+# Prints passed error message before premature exit.
+# Prints everything to >&2 (STDERR).
 # Globals:
 #   Colors: RED, NC
-#   SCRIPT_NAME
 # Arguments:
 #   $1: error message to print
 # Returns:
@@ -525,10 +527,8 @@ download_file()
 #######################################
 exit_script_on_failure()
 {
-  mapfile -t localizedStrings <<< "$(jq -r ".error.${WTWITCH_LANG}, .exiting.${WTWITCH_LANG}" <<< "${TRANSLATIONS}")"
-
   if [[ $# -gt 0 ]]; then
-    printf "\n %b%s%b: %s\n\n %s %s.\n%b" "${RED}" "${localizedStrings[0]}" "${NC}" "$1" "${localizedStrings[1]}" "${SCRIPT_NAME}" "${NC}" >&2
+    printf "\n %b%s%b: %s\n" "${RED}" "$(get_translation error)" "${NC}" "$1" >&2
   fi
 
   clean_up
@@ -536,27 +536,12 @@ exit_script_on_failure()
 }
 
 #######################################
-# Extracts an argument from a --flag=argument.
-# Globals:
-#   none
-# Arguments:
-#   $1: full --flag=argument string
-# Returns:
-#   extracted argument
-#######################################
-extract_argument()
-{
-  # From:
-  # https://stackoverflow.com/questions/7069682/how-to-get-arguments-with-flags-in-bash/7069755#7069755
-  # Updated to use variable search replace instead of sed
-  printf "%s" "${1#--*[ =]}"
-}
-
-#######################################
-# Returns the game name for a specified game ID. Attempts to get game name from
-# cache, but if game ID not present, retrieves it from the Twitch API.
+# Returns the game name for a specified game ID. 
+# Attempts to get game name from cache, but if game
+# ID is not present, retrieves game name from Twitch API.
 # Globals:
 #   CACHE_GAME_ID_FILE
+#   TWITCH_API_URL
 # Arguments:
 #   $1: game ID to get game name of
 # Returns:
@@ -608,8 +593,8 @@ get_translation()
 }
 
 #######################################
-# This is a simple wrapper around a case statement to allow
-# for simple string comparisons against globs.
+# This is a simple wrapper around a case statement to
+# allow for simple string comparisons against globs.
 # Copyright (C) 2016-2019 Dylan Araps
 # Globals:
 #   none
@@ -636,13 +621,14 @@ glob()
 #   none
 #######################################
 to_lowercase() {
-    printf '%s\n' "${1,,}"
+  printf "%s\n" "${1,,}"
 }
 
 #######################################
 # Notifies the user if streaming failed.
 # Globals:
-#   none
+#   WTWITCH_LANG
+#   TRANSLATIONS
 # Arguments:
 #   $1: name of streamer
 #   $2: error message to print
@@ -674,7 +660,7 @@ write_setting()
 }
 
 #######################################
-# Invalidates the cache generated from -c/--check.
+# Invalidates the cache generated from [c]heck command.
 # Globals:
 #   none
 # Arguments:
@@ -692,10 +678,12 @@ invalidate_cache()
 # -----------------------------------------
 
 #######################################
-# Changes the default player in $CONFIG_FILE that gets passed to streamlink.
+# Changes the default player in $CONFIG_FILE that
+# gets passed to streamlink.
 # Globals:
 #   Colors: ORANGE, NC
-#   useColors
+#   WTWITCH_LANG
+#   TRANSLATIONS
 # Arguments:
 #   $1: player to set as default
 # Returns:
@@ -732,7 +720,8 @@ change_player()
 }
 
 #######################################
-# Changes the default quality in $CONFIG_FILE that gets passed to streamlink.
+# Changes the default quality in $CONFIG_FILE that
+# gets passed to streamlink.
 # Globals:
 #   none
 # Arguments:
@@ -770,13 +759,18 @@ change_quality()
 }
 
 #######################################
-# Checks to see which subscribed Twitch streams are online and prints the user's settings.
+# Checks to see which subscribed Twitch streams
+# are online and prints the user's settings.
 # Globals:
+#   CONFIG_FILE
+#   WTWITCH_LANG
+#   TRANSLATIONS
 #   CACHE_EXPIRY_TIME
 #   CACHE_OFFLINE_TEXT_FILE
 #   CACHE_ONLINE_TEXT_FILE
-#   CONFIG_FILE
+#   TWITCH_API_URL
 #   DEBUGGING
+#   CURRENT_TIME_UNIX
 #   userPlayer
 #   userQuality
 #   userSubscriptions
@@ -816,7 +810,7 @@ check_twitch_streams()
     # If the last subsription update is null (e.g. the subscriptions have never been checked), OR
     # if the time between now and the last subscription update is greater than the cache expiry time, OR
     # if either of the cache files do NOT exist yet
-    if  [[ "${lastSubscriptionUpdate}" == "null" ]] || [[ $dateDiff -gt $CACHE_EXPIRY_TIME ]] \
+    if  [[ "${lastSubscriptionUpdate}" == "null" ]] || [[ ${dateDiff} -gt ${CACHE_EXPIRY_TIME} ]] \
     || [[ ! -f "${CACHE_ONLINE_TEXT_FILE}" ]] || [[ ! -f "${CACHE_OFFLINE_TEXT_FILE}" ]]; then
       # Remove old cache files
       clean_up
@@ -840,6 +834,8 @@ check_twitch_streams()
       else
         get_offline_streams "${allStreamerJson}" &
       fi
+
+      readonly CURRENT_TIME_UNIX="$(LANG=C date +%s)"
 
       # Pass each streamer json data to check_twitch_streams_helper to parse,
       # get game name for, and print
@@ -873,7 +869,7 @@ check_twitch_streams()
       wait
 
       # Update lastSubscriptionUpdate time
-      write_setting ".lastSubscriptionUpdate" "$(LANG=C date +%s)" &
+      write_setting ".lastSubscriptionUpdate" "${CURRENT_TIME_UNIX}" &
     fi
 
     printf "\n"
@@ -893,10 +889,10 @@ check_twitch_streams()
 }
 
 #######################################
-# Used by check_twitch_streams to figure out the streamers that are offline.
+# Used by check_twitch_streams to figure out the
+# streamers that are offline.
 # Globals:
 #   DEBUGGING
-#   userSubscriptions
 # Arguments:
 #   $1: "${allStreamerJson}" to compare with user subscriptions
 # Returns:
@@ -919,9 +915,11 @@ get_offline_streams()
 }
 
 #######################################
-# Used by get_offline_streams to figure out the streamers that are offline.
+# Used by get_offline_streams to figure out the
+# streamers that are offline.
 # Globals:
 #   Colors: NC, GREY
+#   LAST_SEEN_DIRECTORY
 #   CACHE_OFFLINE_TEXT_FILE
 # Arguments:
 #   $1: streamer to check
@@ -931,21 +929,29 @@ get_offline_streams()
 #######################################
 get_offline_streams_helper()
 {
+  local lastSeen=""
+  local -r lastSeenFile="${LAST_SEEN_DIRECTORY}/$1"
+
+  if [[ -f "${lastSeenFile}" ]]; then
+    lastSeen=", last online $(date -d "@$(<"${lastSeenFile}")" "+%x")"
+  fi
+
   # If the streamer to check is not found in json, then it is offline
   if [[ "$2" != *"$1"* ]]; then
-    printf "   %b%s%b\n" "${GREY}" "$1" "${NC}" >> "${CACHE_OFFLINE_TEXT_FILE}"
+    printf "   %b%s%s%b\n" "${GREY}" "$1" "${lastSeen}" "${NC}" >> "${CACHE_OFFLINE_TEXT_FILE}"
   fi
 }
 
 #######################################
-# Used by check_twitch_streams to facilitate multi-process fetching and parsing of json files.
+# Used by check_twitch_streams to facilitate
+# multi-process fetching and parsing of json data.
 # Globals:
-#   Colors: LIGHTGREEN, NC, ORANGE, GREY
-#   CACHE_OFFLINE_TEXT_FILE
-#   CACHE_ONLINE_TEXT_FILE
+#   Colors: LIGHTGREEN, NC, ORANGE
+#   CURRENT_TIME_UNIX
+#   LAST_SEEN_DIRECTORY
 #   TERMINAL_WIDTH
 #   TITLE_CHARACTERS
-#   TWITCH_API_URL
+#   CACHE_ONLINE_TEXT_FILE
 # Arguments:
 #   none
 # Returns:
@@ -954,6 +960,9 @@ get_offline_streams_helper()
 check_twitch_streams_helper()
 {
   mapfile -t streamerData <<< "$(jq -r ".user_name, .game_id, .title" <<< "$1")"
+
+  # Update last seen time value
+  printf "%s" "${CURRENT_TIME_UNIX}" > "${LAST_SEEN_DIRECTORY}/$(to_lowercase "${streamerData[0]}")"
 
   # Get stream game name from game ID
   local streamGame
@@ -976,9 +985,11 @@ check_twitch_streams_helper()
 #######################################
 # Lists the top streamers for a specified game.
 # Globals:
+#   WTWITCH_LANG
+#   TRANSLATIONS
+#   TWITCH_API_URL
 #   CACHE_MISC_TEXT_FILE
 #   DEBUGGING
-#   TWITCH_API_URL
 # Arguments:
 #   $1: game to list top streamers of
 # Returns:
@@ -1038,10 +1049,9 @@ list_streamers_of_game()
 }
 
 #######################################
-# Facilitates multi-process parsing of json files.
+# Facilitates multi-process parsing of json data.
 # Globals:
 #   Colors: TURQOISE, NC, ORANGE
-#   CACHE_MISC_TEXT_FILE
 #   TERMINAL_WIDTH
 #   TITLE_CHARACTERS
 # Arguments:
@@ -1058,21 +1068,17 @@ print_stream_info()
   mapfile -t streamerData <<< "$(jq -r ".data[$1].viewer_count, .data[$1].game_id, .data[$1].title" <<< "$2")"
 
   # Do not show streamer if blocked
-  if [[ "${blocklist}" == *"$(to_lowercase "$3")"* ]]; then
-    exit 0
-  fi
+  [[ "${blocklist}" == *"$(to_lowercase "$3")"* ]] && exit
 
   # If streamer data is empty, exit
-  if [[ "${streamerData[1]:-x}" == "x" ]]; then
-    exit
-  fi
+  [[ -z "${streamerData[1]:-}" ]] && exit
 
   # Get streamer-set stream name
   local streamName=""
 
   # Add game name to final string if $5 is present
   local additionalText=""
-  if [[ "$*" == *"--print-game"* ]]; then
+  if [[ -n "${5:-}" ]]; then
     additionalText="$(get_game_name "${streamerData[1]}"), "
   fi
 
@@ -1090,14 +1096,15 @@ print_stream_info()
 }
 
 #######################################
-# Lists the top games and streamers on Twitch.
+# Lists the top games and streams on Twitch.
 # Globals:
 #   Colors: PURPLE, NC
-#   CACHE_MISC_TEXT_FILE
-#   CACHE_TOP_STREAMS_TEXT_FILE
+#   WTWITCH_LANG
+#   TRANSLATIONS
 #   DEBUGGING
 #   TWITCH_API_URL
-#   useColors
+#   CACHE_MISC_TEXT_FILE
+#   CACHE_TOP_STREAMS_TEXT_FILE
 # Arguments:
 #   none
 # Returns:
@@ -1147,9 +1154,9 @@ list_top()
 #######################################
 # Lists the top streams on Twitch.
 # Globals:
-#   CACHE_TOP_STREAMS_TEXT_FILE
-#   DEBUGGING
 #   TWITCH_API_URL
+#   DEBUGGING
+#   CACHE_TOP_STREAMS_TEXT_FILE
 # Arguments:
 #   none
 # Returns:
@@ -1222,9 +1229,9 @@ stream()
     fi
 
     if [[ "${WTWITCH_LANG}" == "de" ]]; then
-      mpvWindowTitle="$1 ${localizedStrings[6]} ${localizedStrings[5]}"
+      local -r mpvWindowTitle="$1 ${localizedStrings[6]} ${localizedStrings[5]}"
     else
-      mpvWindowTitle="${localizedStrings[5]} $1 ${localizedStrings[6]}"
+      local -r mpvWindowTitle="${localizedStrings[5]} $1 ${localizedStrings[6]}"
     fi
 
     streamlink -p "${userPlayer}" --title "${mpvWindowTitle} (\\\${{video-params/h}}p \\\${{estimated-vf-fps}}fps)" --twitch-disable-ads "https://www.twitch.tv/$1" "${userQuality}" || stream_failure_notify "$1" "$1's ${localizedStrings[4]} ${userQuality}."
@@ -1268,7 +1275,8 @@ subscribe()
 }
 
 #######################################
-# Changes the useColor value in $CONFIG_FILE that determines if wtwitch output is colorful.
+# Changes the useColor value in $CONFIG_FILE that
+# determines if wtwitch output is colorful.
 # Globals:
 #   Colors: GREEN, NC
 #   useColors
@@ -1288,7 +1296,7 @@ toggle_colors()
     local -r toPrint="$(get_translation colors_off)"
   else
     # "Re-fill" green from empty
-    GREEN="$(tput bold && tput setaf 2)"
+    GREEN="\e[1m\e[32m"
 
     write_setting ".colors" "true"
     local -r toPrint="$(get_translation colors_on)"
@@ -1304,6 +1312,7 @@ toggle_colors()
 # Unsubscribes from streamer(s).
 # Globals:
 #   CONFIG_FILE
+#   LAST_SEEN_DIRECTORY
 # Arguments:
 #   $@: streamer(s) to unsubscribe from
 # Returns:
@@ -1314,6 +1323,7 @@ unsubscribe()
   shift
   local streamerToUnsubscribeFrom
   local tmpJson
+  local lastSeenFile
 
   while [[ $# -gt 0 ]]; do
     streamerToUnsubscribeFrom="$(to_lowercase "$1")"
@@ -1325,6 +1335,10 @@ unsubscribe()
     # Remove subscription
     tmpJson="$(jq "del(.subscriptions[] | select(.streamer == \"${streamerToUnsubscribeFrom}\"))" "${CONFIG_FILE}")"
     printf "%s" "${tmpJson}" > "${CONFIG_FILE}"
+
+    # Delete lastSeen file
+    lastSeenFile="${LAST_SEEN_DIRECTORY}/${streamerToUnsubscribeFrom}"
+    [[ -f "${lastSeenFile}" ]] && rm -f "${lastSeenFile}"
 
     printf "\n Unsubscribed from %s.\n" "$1"
 
@@ -1375,7 +1389,7 @@ block()
 # Prints information about how to use this script.
 # Copyright (C) 2016-2019 Dylan Araps
 # Globals:
-#   PROJECT_URL
+#   SCRIPT_NAME
 # Arguments:
 #   none
 # Returns:
@@ -1386,7 +1400,7 @@ print_help()
   printf "%s" "\
 ${SCRIPT_NAME} - terminal user interface for Twitch
 
-=> (no command) [name] - Watch [name] streamer.
+=> [w]atch [name]      - Watch [name] streamer.
 => [s]ub [name(s)]     - Subscribe to [name] streamer.
                          You can subscribe to multiple streamers in one command.
 => [u]nsub [name(s)]   - Unsubscribe from [name] streamer.
@@ -1403,7 +1417,7 @@ ${SCRIPT_NAME} - terminal user interface for Twitch
 => [v]ersion           - Print the current version of wtwitch.
 => [h]elp              - Print this help.
 
-See \"man wtwitch\" for more information.
+See \"man ${SCRIPT_NAME}\" for more information.
 "
 
   exit 0
@@ -1468,7 +1482,7 @@ glob "$1" '[p]*' && [[ -z "${2:-}" ]] &&
 glob "$1" '[q]*' && [[ -z "${2:-}" ]] &&
   exit_script_on_failure "$(get_translation flags_no_quality)"
 
-glob "$1" '[su]*' && [[ -z "${2:-}" ]] &&
+glob "$1" '[suw]*' && [[ -z "${2:-}" ]] &&
   exit_script_on_failure "$(get_translation flags_no_streamer)"
 
 case "$1" in
@@ -1483,11 +1497,11 @@ case "$1" in
   u*) unsubscribe "$@" ;;
   b*) block "$@" ;;
   v*) print_version ;;
-  *)
+  w*)
     if [[ "${userQuality}" == "audio_only" ]] || [[ "${DEBUGGING}" == "on" ]]; then
-      stream "$1"
+      stream "$2"
     else
-      stream "$1" &> /dev/null &
+      stream "$2" &> /dev/null &
     fi
   ;;
 esac
